# Generated by Django 3.0.2 on 2021-11-01 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0003_invitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circle',
            old_name='aabout',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='circle',
            old_name='memebers',
            new_name='members',
        ),
    ]
