# Generated by Django 3.0.2 on 2021-11-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0004_auto_20211101_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Circles wont be deleted from db, they will just get inactive'),
        ),
    ]
